version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: notification_center_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      notification_net:
        ipv4_address: 172.20.0.10

  order.api:
    image: order-api-image
    container_name: order_api_container
    build:
      context: .
      dockerfile: Order.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - RabbitMQ__HostName=172.20.0.10
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - rabbitmq
    networks:
      notification_net:

  notification.consumer:
    image: notification-consumer-image
    container_name: notification_consumer_container
    build:
      context: .
      dockerfile: Notification.Consumer/Dockerfile
    environment:
      - RabbitMQ__HostName=172.20.0.10
    depends_on:
      - rabbitmq
    networks:
      notification_net:

networks:
  notification_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16